--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 1/11/2023 5:46:03 AM
-- Server version: 8.0.28
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE radius;

--
-- Drop table `admin`
--
DROP TABLE IF EXISTS admin;

--
-- Drop table `nas`
--
DROP TABLE IF EXISTS nas;

--
-- Drop event `event_of_day`
--
DROP EVENT IF EXISTS event_of_day;

--
-- Drop procedure `proc_create_partition_day`
--
DROP PROCEDURE IF EXISTS proc_create_partition_day;

--
-- Drop event `event_of_month`
--
DROP EVENT IF EXISTS event_of_month;

--
-- Drop procedure `proc_drop_partition`
--
DROP PROCEDURE IF EXISTS proc_drop_partition;

--
-- Drop procedure `procedure1`
--
DROP PROCEDURE IF EXISTS procedure1;

--
-- Drop event `event_of_minute`
--
DROP EVENT IF EXISTS event_of_minute;

--
-- Drop table `online_user`
--
DROP TABLE IF EXISTS online_user;

--
-- Drop table `realm`
--
DROP TABLE IF EXISTS realm;

--
-- Drop table `offline_user`
--
DROP TABLE IF EXISTS offline_user;

--
-- Drop table `sidebar_tree`
--
DROP TABLE IF EXISTS sidebar_tree;

--
-- Drop procedure `proc_create_partition_month`
--
DROP PROCEDURE IF EXISTS proc_create_partition_month;

--
-- Drop view `view_radcheck`
--
DROP VIEW IF EXISTS view_radcheck CASCADE;

--
-- Drop procedure `my_insert_radcheck`
--
DROP PROCEDURE IF EXISTS my_insert_radcheck;

--
-- Drop table `radcheck`
--
DROP TABLE IF EXISTS radcheck;

--
-- Drop table `radpostauth`
--
DROP TABLE IF EXISTS radpostauth;

--
-- Drop view `view_radreply`
--
DROP VIEW IF EXISTS view_radreply CASCADE;

--
-- Drop table `account_info`
--
DROP TABLE IF EXISTS account_info;

--
-- Drop table `radreply`
--
DROP TABLE IF EXISTS radreply;

--
-- Drop function `get_radius_class_attr`
--
DROP FUNCTION IF EXISTS get_radius_class_attr;

--
-- Drop function `get_radius_hw_attr`
--
DROP FUNCTION IF EXISTS get_radius_hw_attr;

--
-- Drop function `get_radius_zte_attr`
--
DROP FUNCTION IF EXISTS get_radius_zte_attr;

--
-- Set default database
--
USE radius;

DELIMITER $$

--
-- Create function `get_radius_zte_attr`
--
CREATE DEFINER = 'root'@'%'
FUNCTION get_radius_zte_attr (ulimit int, dlimit int)
RETURNS varchar(100) CHARSET utf8mb4
DETERMINISTIC
BEGIN
  DECLARE ustr,
          dstr varchar(100);
  IF (dlimit = 0
    OR ulimit = 0) THEN
    RETURN NULL;
  END IF;
  SET ustr := HEX(ulimit);
  IF (LENGTH(ustr) > 8
    OR ulimit = 0) THEN
    SET ustr := 'FFFFFFFF';
  END IF;
  SET ustr := LPAD(ustr, 8, '0');
  SET dstr := HEX(dlimit);
  IF (LENGTH(dstr) > 8
    OR dlimit = 0) THEN
    SET dstr := 'FFFFFFFF';
  END IF;
  SET dstr := LPAD(dstr, 8, '0');
  RETURN CONCAT('0x00000F3E5906', dstr, '5306', ustr);

END
$$

--
-- Create function `get_radius_hw_attr`
--
CREATE DEFINER = 'root'@'%'
FUNCTION get_radius_hw_attr (ulimit int, dlimit int)
RETURNS varchar(100) CHARSET utf8mb4
DETERMINISTIC
BEGIN

  DECLARE ustr,
          dstr varchar(100);
  IF (dlimit = 0
    OR ulimit = 0) THEN
    RETURN NULL;
  END IF;

  SET ustr := HEX(ulimit * 1024);
  IF (LENGTH(ustr) > 8
    OR ulimit = 0) THEN
    SET ustr := 'FFFFFFFF';
  END IF;
  SET ustr := LPAD(ustr, 8, '0');

  SET dstr := HEX(dlimit * 1024);
  IF (LENGTH(dstr) > 8
    OR dlimit = 0) THEN
    SET dstr := 'FFFFFFFF';
  END IF;
  SET dstr := LPAD(dstr, 8, '0');

  RETURN CONCAT('0x000007DB0206', dstr, '0306', dstr, '0506', ustr, '0606', ustr);
END
$$

--
-- Create function `get_radius_class_attr`
--
CREATE DEFINER = 'root'@'%'
FUNCTION get_radius_class_attr (ulimit int, dlimit int)
RETURNS varchar(100) CHARSET utf8mb4
DETERMINISTIC
BEGIN
  #本函数输入上行速率，下行速率，转换为 radius client 接受的class 格式的字符串输出
  #若用Class属性携带CAR参数，长度最短为32位，且字符串中必须是0~9之间的数字，不能含有其它字符。将前32字节分成4个8字节
  DECLARE ustr,
          dstr varchar(100);

  SELECT
    CONCAT(ulimit * 1024, '') INTO ustr
  FROM dual;
  IF (LENGTH(ustr) > 8
    OR ulimit = 0) THEN
    #规定最大只能8位，超出无效，需要用厂家专用的26号radius属性进行调速
    RETURN NULL;
  END IF;
  SET ustr := LPAD(ustr, 8, '0');

  SELECT
    CONCAT(dlimit * 1024, '') INTO dstr
  FROM dual;
  IF (LENGTH(dstr) > 8
    OR dlimit = 0) THEN
    #规定最大只能8位，超出无效，需要用厂家专用的26号radius属性进行调速
    RETURN NULL;
  END IF;

  SET dstr := LPAD(dstr, 8, '0');

  #class 格式上行峰值速率，上行平均速率，下行峰值速率，下行平均速率
  RETURN CONCAT(ustr, ustr, dstr, dstr);
END
$$

DELIMITER ;

--
-- Create table `radreply`
--
CREATE TABLE radreply (
  id int UNSIGNED NOT NULL AUTO_INCREMENT,
  username varchar(45) NOT NULL DEFAULT '',
  realm varchar(45) NOT NULL DEFAULT '',
  attribute varchar(64) NOT NULL DEFAULT '',
  op char(2) NOT NULL DEFAULT ':=',
  value varchar(253) NOT NULL DEFAULT '',
  account_id varchar(36) NOT NULL,
  is_frozen tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `username` on table `radreply`
--
ALTER TABLE radreply
ADD INDEX username (username (32));

--
-- Create table `account_info`
--
CREATE TABLE account_info (
  id varchar(36) NOT NULL,
  user_name varchar(45) NOT NULL COMMENT '该字段和realm的组合通过唯一约束保证不重复',
  realm varchar(45) NOT NULL DEFAULT '',
  user_password varchar(45) NOT NULL DEFAULT '',
  auth_mode int UNSIGNED ZEROFILL NOT NULL DEFAULT 0000000000,
  is_frozen tinyint NOT NULL DEFAULT 0,
  admin_name varchar(45) NOT NULL DEFAULT '',
  valid_date datetime DEFAULT CURRENT_TIMESTAMP,
  expire_date datetime DEFAULT NULL,
  modify_date datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '通过update触发器自动维护',
  simual_use_limit int NOT NULL DEFAULT 0,
  byte_remain bigint NOT NULL DEFAULT 0,
  second_remain bigint NOT NULL DEFAULT 0,
  max_session_timeout int NOT NULL DEFAULT 0,
  inbound_car int NOT NULL DEFAULT 0,
  outbound_car int NOT NULL DEFAULT 0,
  qos_profile varchar(45) NOT NULL DEFAULT '' COMMENT 'qos 模板，对应BRAS起的名字',
  update_interval int NOT NULL DEFAULT 0 COMMENT '计费报文间隔',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = '上网用户账号的属性表。方便ui展示和管理，最终要转换到radcheck和radreply的表让radius进程读取才起作用。';

--
-- Create index `id_UNIQUE` on table `account_info`
--
ALTER TABLE account_info
ADD UNIQUE INDEX id_UNIQUE (id) INVISIBLE;

--
-- Create index `user_unique` on table `account_info`
--
ALTER TABLE account_info
ADD UNIQUE INDEX user_unique (user_name, realm);

--
-- Create view `view_radreply`
--
CREATE
DEFINER = 'root'@'%'
VIEW view_radreply
AS
SELECT
  `radreply`.`id` AS `id`,
  CONCAT(`radreply`.`username`, `radreply`.`realm`) AS `UserName`,
  `radreply`.`attribute` AS `Attribute`,
  `radreply`.`value` AS `Value`,
  `radreply`.`op` AS `op`
FROM `radreply`
WHERE (`radreply`.`attribute` NOT IN ('Session-Timeout', 'Acct-Interim-Interval', 'Class'))
UNION ALL
SELECT
  '1000' AS `id`,
  CONCAT(`account_info`.`user_name`, `account_info`.`realm`) AS `UserName`,
  'Session-Timeout' AS `Attribute`,
  `account_info`.`max_session_timeout` AS `Value`,
  ':=' AS `op`
FROM `account_info`
WHERE (`account_info`.`max_session_timeout` <> 0)
UNION ALL
SELECT
  '1001' AS `id`,
  CONCAT(`account_info`.`user_name`, `account_info`.`realm`) AS `UserName`,
  'Acct-Interim-Interval' AS `Attribute`,
  `account_info`.`update_interval` AS `Value`,
  ':=' AS `op`
FROM `account_info`
WHERE (`account_info`.`update_interval` <> 0)
UNION ALL
SELECT
  '1002' AS `id`,
  CONCAT(`account_info`.`user_name`, `account_info`.`realm`) AS `UserName`,
  'Class' AS `Attribute`,
  `GET_RADIUS_CLASS_ATTR`(`account_info`.`inbound_car`, `account_info`.`outbound_car`) AS `VALUE`,
  ':=' AS `op`
FROM `account_info`
WHERE (`GET_RADIUS_CLASS_ATTR`(`account_info`.`inbound_car`, `account_info`.`outbound_car`) IS NOT NULL)
UNION ALL
SELECT
  '1003' AS `id`,
  CONCAT(`account_info`.`user_name`, `account_info`.`realm`) AS `UserName`,
  'Attr-26' AS `Attribute`,
  `GET_RADIUS_HW_ATTR`(`account_info`.`inbound_car`, `account_info`.`outbound_car`) AS `VALUE`,
  ':=' AS `op`
FROM `account_info`
WHERE (`GET_RADIUS_HW_ATTR`(`account_info`.`inbound_car`, `account_info`.`outbound_car`) IS NOT NULL)
UNION ALL
SELECT
  '1004' AS `id`,
  CONCAT(`account_info`.`user_name`, `account_info`.`realm`) AS `UserName`,
  'Attr-26' AS `Attribute`,
  `GET_RADIUS_ZTE_ATTR`(`account_info`.`inbound_car`, `account_info`.`outbound_car`) AS `VALUE`,
  ':=' AS `op`
FROM `account_info`
WHERE (`GET_RADIUS_ZTE_ATTR`(`account_info`.`inbound_car`, `account_info`.`outbound_car`) IS NOT NULL);

--
-- Create table `radpostauth`
--
CREATE TABLE radpostauth (
  id bigint NOT NULL AUTO_INCREMENT,
  username varchar(45) NOT NULL DEFAULT '',
  realm varchar(45) NOT NULL DEFAULT '',
  pass varchar(64) NOT NULL DEFAULT '',
  reply varchar(32) NOT NULL DEFAULT '',
  callingstationid varchar(50) NOT NULL DEFAULT '',
  nasidentifier varchar(80) NOT NULL DEFAULT '',
  authdate datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  _class varchar(64) DEFAULT NULL,
  PRIMARY KEY (id, authdate)
)
ENGINE = INNODB,
AUTO_INCREMENT = 86,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = '认证日志表，按天分区，保留7天'
PARTITION BY RANGE (TO_DAYS(`authdate`))
(
PARTITION p20230106 VALUES LESS THAN (738892),
PARTITION p20230107 VALUES LESS THAN (738893),
PARTITION p20230108 VALUES LESS THAN (738894),
PARTITION p20230109 VALUES LESS THAN (738895),
PARTITION p20230110 VALUES LESS THAN (738896),
PARTITION p20230111 VALUES LESS THAN (738897),
PARTITION max VALUES LESS THAN MAXVALUE
);

--
-- Create index `username` on table `radpostauth`
--
ALTER TABLE radpostauth
ADD INDEX username (username);

--
-- Create table `radcheck`
--
CREATE TABLE radcheck (
  id int UNSIGNED NOT NULL AUTO_INCREMENT,
  username varchar(45) NOT NULL DEFAULT '',
  realm varchar(45) NOT NULL DEFAULT '',
  attribute varchar(64) NOT NULL DEFAULT '',
  op char(2) NOT NULL DEFAULT ':=',
  value varchar(253) NOT NULL DEFAULT '',
  account_id varchar(36) NOT NULL,
  is_frozen tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 24,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `ix_rcheck_username` on table `radcheck`
--
ALTER TABLE radcheck
ADD INDEX ix_rcheck_username (username);

DELIMITER $$

--
-- Create procedure `my_insert_radcheck`
--
CREATE DEFINER = 'root'@'%'
PROCEDURE my_insert_radcheck (IN cnt int)
BEGIN
  DECLARE n int DEFAULT 0;
loopname:
  LOOP
    INSERT INTO `radcheck` (`username`, `attribute`, `op`, `value`)
      VALUES (CONCAT('test_', n), 'User-Password', ':=', '1234');
    SET n = n + 1;
    IF n >= cnt THEN
      LEAVE loopname;
    END IF;
  END LOOP loopname;
END
$$

DELIMITER ;

--
-- Create view `view_radcheck`
--
CREATE
DEFINER = 'root'@'%'
VIEW view_radcheck
AS
SELECT
  `radcheck`.`id` AS `id`,
  CONCAT(`radcheck`.`username`, `radcheck`.`realm`) AS `UserName`,
  `radcheck`.`attribute` AS `Attribute`,
  `radcheck`.`value` AS `Value`,
  `radcheck`.`op` AS `op`
FROM `radcheck`
WHERE (`radcheck`.`attribute` NOT IN ('Cleartext-Password', 'Simultaneous-Use'))
UNION ALL
SELECT
  '1100' AS `id`,
  CONCAT(`account_info`.`user_name`, `account_info`.`realm`) AS `UserName`,
  'Cleartext-Password' AS `Attribute`,
  `account_info`.`user_password` AS `Value`,
  ':=' AS `op`
FROM `account_info`
WHERE ((`account_info`.`is_frozen` = 0)
AND (((`account_info`.`valid_date` IS NOT NULL)
AND (`account_info`.`valid_date` < NOW()))
OR (`account_info`.`valid_date` IS NULL))
AND (((`account_info`.`expire_date` IS NOT NULL)
AND (`account_info`.`expire_date` > NOW()))
OR (`account_info`.`expire_date` IS NULL))
AND (`account_info`.`byte_remain` >= 0)
AND (`account_info`.`second_remain` >= 0))
UNION ALL
SELECT
  '1101' AS `id`,
  CONCAT(`account_info`.`user_name`, `account_info`.`realm`) AS `UserName`,
  'Simultaneous-Use' AS `Attribute`,
  `account_info`.`simual_use_limit` AS `Value`,
  ':=' AS `op`
FROM `account_info`
WHERE (`account_info`.`simual_use_limit` > 0);

DELIMITER $$

--
-- Create procedure `proc_create_partition_month`
--
CREATE DEFINER = 'root'@'%'
PROCEDURE proc_create_partition_month (IN `tableName` varchar(128) CHARSET utf8,
IN `timeColName` varchar(128) CHARSET utf8)
BEGIN
  #本存储过程会为指定的`tableName`和`timeColName`创建分区表，每天只创建一个，重复调用不会重复创建。
  DECLARE is_partition_exist int;
  DECLARE p_name varchar(16);
  DECLARE p_value varchar(16);
  DECLARE nextDate date;

  #测试是否存在任意分区
  SELECT
    COUNT(partition_name) INTO is_partition_exist
  FROM INFORMATION_SCHEMA.partitions
  WHERE TABLE_NAME = tableName;
  IF is_partition_exist = 0 THEN #如果没有任何分区则，则创建分区函数和一个max分区       
    SET @v_add = CONCAT('ALTER TABLE ', tableName, '  PARTITION BY RANGE (TO_DAYS(', timeColName, '))
( PARTITION max VALUES LESS THAN MAXVALUE ENGINE = INNODB)');

    SELECT
      @v_add;
    PREPARE stmt FROM @v_add;
    EXECUTE stmt;
  END IF;

  #测试是否存在max分区
  SELECT
    COUNT(PARTITION_DESCRIPTION) INTO is_partition_exist
  FROM INFORMATION_SCHEMA.partitions
  WHERE TABLE_NAME = tableName
  AND PARTITION_DESCRIPTION = 'MAXVALUE';
  IF is_partition_exist = 0 THEN #如果没有max分区则创建之       
    SET @v_add = CONCAT('ALTER TABLE ', tableName, ' ADD PARTITION (PARTITION max VALUES LESS THAN (MAXVALUE) ENGINE = INNODB);');
    SELECT
      @v_add;
    PREPARE stmt FROM @v_add;
    EXECUTE stmt;

  END IF;

  SELECT
    DATE_ADD(CURDATE() - DAY(CURDATE()) + 1, INTERVAL 1 MONTH) INTO nextDate
  FROM DUAL;

  SET p_name = CONCAT('p', DATE_FORMAT(nextDate, '%Y%m%d'));
  SET p_value = TO_DAYS(nextDate) + 1;

  #测试是否存在当月分区
  SELECT
    COUNT(PARTITION_DESCRIPTION) INTO is_partition_exist
  FROM INFORMATION_SCHEMA.partitions
  WHERE TABLE_NAME = tableName
  AND PARTITION_DESCRIPTION = p_value;

  IF is_partition_exist = 0 THEN #如果没有当月分区则创建之
    SET @v_add = CONCAT('ALTER table ', tableName
    , ' REORGANIZE PARTITION max INTO(PARTITION '
    , p_name
    , ' values less than ('
    , p_value, '),PARTITION max VALUES LESS THAN(MAXVALUE))');
    SELECT
      @v_add;
    PREPARE stmt FROM @v_add;
    EXECUTE stmt;
  END IF;
  DEALLOCATE PREPARE stmt;
END
$$

DELIMITER ;

--
-- Create table `sidebar_tree`
--
CREATE TABLE sidebar_tree (
  id varchar(36) NOT NULL,
  label varchar(45) DEFAULT NULL,
  pid varchar(36) DEFAULT NULL,
  type tinyint DEFAULT NULL,
  owner varchar(45) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 2340,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = '管理后台的左侧树控件节点集合';

--
-- Create index `id_UNIQUE` on table `sidebar_tree`
--
ALTER TABLE sidebar_tree
ADD UNIQUE INDEX id_UNIQUE (id);

--
-- Create table `offline_user`
--
CREATE TABLE offline_user (
  radacctid bigint NOT NULL AUTO_INCREMENT,
  acctsessionid varchar(64) NOT NULL DEFAULT '',
  acctuniqueid varchar(32) NOT NULL DEFAULT '',
  username varchar(45) NOT NULL DEFAULT '',
  realm varchar(45) NOT NULL DEFAULT '',
  nasidentifier varchar(80) NOT NULL DEFAULT '',
  nasipaddress varchar(15) NOT NULL DEFAULT '',
  nasportid varchar(120) DEFAULT NULL,
  nasporttype varchar(32) DEFAULT NULL,
  acctstarttime datetime DEFAULT NULL,
  acctupdatetime datetime DEFAULT NULL,
  acctstoptime datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  acctinterval int DEFAULT NULL,
  acctsessiontime int DEFAULT NULL,
  acctauthentic varchar(32) DEFAULT NULL,
  connectinfo_start varchar(128) DEFAULT NULL,
  connectinfo_stop varchar(128) DEFAULT NULL,
  acctinputoctets bigint DEFAULT NULL,
  acctoutputoctets bigint DEFAULT NULL,
  calledstationid varchar(50) NOT NULL DEFAULT '',
  callingstationid varchar(50) NOT NULL DEFAULT '',
  acctterminatecause varchar(32) NOT NULL DEFAULT '',
  servicetype varchar(32) DEFAULT NULL,
  framedprotocol varchar(32) DEFAULT NULL,
  framedipaddress varchar(15) NOT NULL DEFAULT '',
  framedipv6address varchar(45) NOT NULL DEFAULT '',
  framedipv6prefix varchar(45) NOT NULL DEFAULT '',
  framedinterfaceid varchar(44) NOT NULL DEFAULT '',
  delegatedipv6prefix varchar(45) NOT NULL DEFAULT '',
  _class varchar(64) DEFAULT NULL,
  kickme int NOT NULL DEFAULT 0,
  PRIMARY KEY (radacctid, acctstoptime)
)
ENGINE = INNODB,
AUTO_INCREMENT = 1232337,
AVG_ROW_LENGTH = 2184,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci
PARTITION BY RANGE (TO_DAYS(`acctstoptime`))
(
PARTITION p20230201 VALUES LESS THAN (738918),
PARTITION max VALUES LESS THAN MAXVALUE
);

--
-- Create index `acctsessionid` on table `offline_user`
--
ALTER TABLE offline_user
ADD INDEX acctsessionid (acctsessionid);

--
-- Create index `acctstarttime` on table `offline_user`
--
ALTER TABLE offline_user
ADD INDEX acctstarttime (acctstarttime);

--
-- Create index `acctstoptime` on table `offline_user`
--
ALTER TABLE offline_user
ADD INDEX acctstoptime (acctstoptime);

--
-- Create index `acctuniqueid` on table `offline_user`
--
ALTER TABLE offline_user
ADD UNIQUE INDEX acctuniqueid (acctuniqueid, acctstoptime);

--
-- Create index `callingstationid` on table `offline_user`
--
ALTER TABLE offline_user
ADD INDEX callingstationid (callingstationid);

--
-- Create index `framedipaddress` on table `offline_user`
--
ALTER TABLE offline_user
ADD INDEX framedipaddress (framedipaddress);

--
-- Create index `nasipaddress` on table `offline_user`
--
ALTER TABLE offline_user
ADD INDEX nasipaddress (nasipaddress);

--
-- Create index `username` on table `offline_user`
--
ALTER TABLE offline_user
ADD INDEX username (username);

--
-- Create table `realm`
--
CREATE TABLE realm (
  id varchar(36) NOT NULL,
  realm varchar(45) DEFAULT NULL,
  node_id varchar(36) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = '记录管理节点和域（realm）的对应关系。';

--
-- Create index `id_UNIQUE` on table `realm`
--
ALTER TABLE realm
ADD UNIQUE INDEX id_UNIQUE (id);

--
-- Create index `realm_UNIQUE` on table `realm`
--
ALTER TABLE realm
ADD UNIQUE INDEX realm_UNIQUE (realm);

--
-- Create table `online_user`
--
CREATE TABLE online_user (
  radacctid bigint NOT NULL AUTO_INCREMENT,
  acctsessionid varchar(64) NOT NULL DEFAULT '',
  acctuniqueid varchar(32) NOT NULL DEFAULT '',
  username varchar(45) NOT NULL DEFAULT '',
  realm varchar(45) NOT NULL DEFAULT '',
  nasidentifier varchar(80) NOT NULL DEFAULT '',
  nasipaddress varchar(15) NOT NULL DEFAULT '',
  nasportid varchar(120) DEFAULT NULL,
  nasporttype varchar(32) DEFAULT NULL,
  acctstarttime datetime DEFAULT NULL,
  acctupdatetime datetime DEFAULT NULL,
  acctstoptime datetime DEFAULT NULL,
  acctinterval int DEFAULT NULL,
  acctsessiontime int DEFAULT NULL,
  acctauthentic varchar(32) DEFAULT NULL,
  connectinfo_start varchar(128) DEFAULT NULL,
  connectinfo_stop varchar(128) DEFAULT NULL,
  acctinputoctets bigint DEFAULT NULL,
  acctoutputoctets bigint DEFAULT NULL,
  calledstationid varchar(50) NOT NULL DEFAULT '',
  callingstationid varchar(50) NOT NULL DEFAULT '',
  acctterminatecause varchar(32) NOT NULL DEFAULT '',
  servicetype varchar(32) DEFAULT NULL,
  framedprotocol varchar(32) DEFAULT NULL,
  framedipaddress varchar(15) NOT NULL DEFAULT '',
  framedipv6address varchar(45) NOT NULL DEFAULT '',
  framedipv6prefix varchar(45) NOT NULL DEFAULT '',
  framedinterfaceid varchar(44) NOT NULL DEFAULT '',
  delegatedipv6prefix varchar(45) NOT NULL DEFAULT '',
  _class varchar(64) DEFAULT NULL,
  kickme int NOT NULL DEFAULT 0,
  PRIMARY KEY (radacctid)
)
ENGINE = INNODB,
AUTO_INCREMENT = 170,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `acctinterval` on table `online_user`
--
ALTER TABLE online_user
ADD INDEX acctinterval (acctinterval);

--
-- Create index `acctsessionid` on table `online_user`
--
ALTER TABLE online_user
ADD INDEX acctsessionid (acctsessionid);

--
-- Create index `acctsessiontime` on table `online_user`
--
ALTER TABLE online_user
ADD INDEX acctsessiontime (acctsessiontime);

--
-- Create index `acctstarttime` on table `online_user`
--
ALTER TABLE online_user
ADD INDEX acctstarttime (acctstarttime);

--
-- Create index `acctstoptime` on table `online_user`
--
ALTER TABLE online_user
ADD INDEX acctstoptime (acctstoptime);

--
-- Create index `acctuniqueid` on table `online_user`
--
ALTER TABLE online_user
ADD UNIQUE INDEX acctuniqueid (acctuniqueid);

--
-- Create index `class` on table `online_user`
--
ALTER TABLE online_user
ADD INDEX class (_class);

--
-- Create index `delegatedipv6prefix` on table `online_user`
--
ALTER TABLE online_user
ADD INDEX delegatedipv6prefix (delegatedipv6prefix);

--
-- Create index `framedinterfaceid` on table `online_user`
--
ALTER TABLE online_user
ADD INDEX framedinterfaceid (framedinterfaceid);

--
-- Create index `framedipaddress` on table `online_user`
--
ALTER TABLE online_user
ADD INDEX framedipaddress (framedipaddress);

--
-- Create index `framedipv6address` on table `online_user`
--
ALTER TABLE online_user
ADD INDEX framedipv6address (framedipv6address);

--
-- Create index `framedipv6prefix` on table `online_user`
--
ALTER TABLE online_user
ADD INDEX framedipv6prefix (framedipv6prefix);

--
-- Create index `nasipaddress` on table `online_user`
--
ALTER TABLE online_user
ADD INDEX nasipaddress (nasipaddress);

--
-- Create index `username` on table `online_user`
--
ALTER TABLE online_user
ADD INDEX username (username);

DELIMITER $$

--
-- Create event `event_of_minute`
--
CREATE 
	DEFINER = 'root'@'%'
EVENT event_of_minute
	ON SCHEDULE EVERY '1' MINUTE
	STARTS '2022-12-16 07:35:48'
	DO 
BEGIN
#我们假设BRAS会定时发送计费更新报文，认为超过3600秒没有更新过在线记录的用户已经下线
UPDATE  radius.online_user SET acctstoptime=NOW() WHERE ABS(TIMESTAMPDIFF(SECOND, NOW(), acctupdatetime))>3600  ;
#我们希望将已经下线的记录’移动‘到offline_user表，因为目标表有触发器又会主动删除源表（online_user）中的对应记录，
#所以不能直接在用 insert into offline_user select from online_user, 而是需要建立一张临时表作为中转
#我们假设记录不多，所以临时表用了内存引擎，如果记录太大要改用其他引擎
CREATE  TEMPORARY  TABLE `temp_user` (
  `radacctid` bigint NOT NULL AUTO_INCREMENT,
  `acctsessionid` varchar(64) NOT NULL DEFAULT '',
  `acctuniqueid` varchar(32) NOT NULL DEFAULT '',
  `username` varchar(45) NOT NULL DEFAULT '',
  `realm` varchar(45) NOT NULL DEFAULT '',
  `nasidentifier` varchar(80) NOT NULL DEFAULT '',
  `nasipaddress` varchar(15) NOT NULL DEFAULT '',
  `nasportid` varchar(120) DEFAULT NULL,
  `nasporttype` varchar(32) DEFAULT NULL,
  `acctstarttime` datetime DEFAULT NULL,
  `acctupdatetime` datetime DEFAULT NULL,
  `acctstoptime` datetime DEFAULT NULL,
  `acctinterval` int DEFAULT NULL,
  `acctsessiontime` int DEFAULT NULL,
  `acctauthentic` varchar(32) DEFAULT NULL,
  `connectinfo_start` varchar(128) DEFAULT NULL,
  `connectinfo_stop` varchar(128) DEFAULT NULL,
  `acctinputoctets` bigint DEFAULT NULL,
  `acctoutputoctets` bigint DEFAULT NULL,
  `calledstationid` varchar(50) NOT NULL DEFAULT '',
  `callingstationid` varchar(50) NOT NULL DEFAULT '',
  `acctterminatecause` varchar(32) NOT NULL DEFAULT '',
  `servicetype` varchar(32) DEFAULT NULL,
  `framedprotocol` varchar(32) DEFAULT NULL,
  `framedipaddress` varchar(15) NOT NULL DEFAULT '',
  `framedipv6address` varchar(45) NOT NULL DEFAULT '',
  `framedipv6prefix` varchar(45) NOT NULL DEFAULT '',
  `framedinterfaceid` varchar(44) NOT NULL DEFAULT '',
  `delegatedipv6prefix` varchar(45) NOT NULL DEFAULT '',
  `_class` varchar(64) DEFAULT NULL,
   kickme int NOT NULL DEFAULT 0,
  PRIMARY KEY (`radacctid`),
  UNIQUE KEY `acctuniqueid` (`acctuniqueid`)

) ENGINE=memory  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

#先拷到临时表
INSERT INTO temp_user
SELECT * FROM online_user WHERE acctstoptime IS NOT NULL ;

#再拷到目标表，目标表的触发器会把源表的对应记录删除
INSERT INTO offline_user SELECT * FROM temp_user  ;
drop table temp_user;

#清理ui上由于删除树节点而被破坏外键关联的元素
DELETE FROM realm  WHERE node_id NOT IN (SELECT id FROM sidebar_tree  );

DELETE FROM admin WHERE nodeid NOT IN (SELECT id FROM sidebar_tree  );
COMMIT;



END
$$

ALTER 
	DEFINER = 'root'@'%'
EVENT event_of_minute
	ENABLE
$$

--
-- Create procedure `procedure1`
--
CREATE DEFINER = 'root'@'%'
PROCEDURE procedure1 ()
BEGIN
  DECLARE acct1 int;
  DECLARE acct2 int;
  DECLARE acct int;
  DECLARE auth int;



  #10分钟内处理的计费报文
  SELECT
    COUNT(*) INTO acct1
  FROM offline_user
  WHERE acctstoptime > NOW() - INTERVAL 10 MINUTE;
  SELECT
    COUNT(*) INTO acct2
  FROM online_user
  WHERE acctupdatetime > NOW() - INTERVAL 10 MINUTE;
  SET acct = acct1 + acct2;

  #10分钟内处理的认证报文
  SELECT
    COUNT(*) INTO auth
  FROM radpostauth
  WHERE authdate > NOW() - INTERVAL 10 MINUTE;

  SELECT
    acct AS acct,
    auth AS auth;
#SELECT SUM(`acctinputoctets`+`acctoutputoctets`) FROM offline_user ;
#SELECT SUM(`acctinputoctets`+`acctoutputoctets`) FROM online_user ; 
#SELECT SUM(`acctsessiontime`) FROM offline_user;
#SELECT SUM(`acctsessiontime`) FROM online_user;

END
$$

--
-- Create procedure `proc_drop_partition`
--
CREATE DEFINER = 'root'@'%'
PROCEDURE proc_drop_partition (IN `tableName` varchar(128) CHARSET utf8, IN `reservePartition` int)
BEGIN
  DECLARE p_id int;
  DECLARE p_name varchar(16);

  SELECT
    COUNT(partition_name) INTO p_id
  FROM INFORMATION_SCHEMA.PARTITIONS
  WHERE TABLE_NAME = tableName;

  IF p_id > reservePartition THEN

    SELECT
      PARTITION_NAME INTO p_name
    FROM INFORMATION_SCHEMA.PARTITIONS
    WHERE TABLE_NAME = tableName
    ORDER BY partition_ordinal_position ASC LIMIT 1;

    IF p_name IS NOT NULL THEN
      SET @v_add = CONCAT('alter table ', tableName, ' drop partition ', p_name);
      PREPARE stmt FROM @v_add;
      EXECUTE stmt;
      DEALLOCATE PREPARE stmt;
    END IF;
  END IF;
END
$$

--
-- Create event `event_of_month`
--
CREATE 
	DEFINER = 'root'@'%'
EVENT event_of_month
	ON SCHEDULE EVERY '1' MONTH
	STARTS '2023-02-01 21:53:47'
	DO 
BEGIN



#创建新分区
call proc_create_partition_month('offline_user','acctstoptime');


#删除最旧的一个分区
call proc_drop_partition( 'offline_user',12);




END
$$

ALTER 
	DEFINER = 'root'@'%'
EVENT event_of_month
	ENABLE
$$

--
-- Create procedure `proc_create_partition_day`
--
CREATE DEFINER = 'root'@'%'
PROCEDURE proc_create_partition_day (IN `tableName` varchar(128) CHARSET utf8, IN `timeColName` varchar(128) CHARSET utf8)
BEGIN
  #本存储过程会为指定的`tableName`和`timeColName`创建分区表，每天只创建一个，重复调用不会重复创建。
  DECLARE is_partition_exist int;
  DECLARE p_name varchar(16);
  DECLARE p_value varchar(16);

  #测试是否存在任意分区
  SELECT
    COUNT(partition_name) INTO is_partition_exist
  FROM INFORMATION_SCHEMA.partitions
  WHERE TABLE_NAME = tableName;
  IF is_partition_exist = 0 THEN #如果没有任何分区则，则创建分区函数和一个max分区       
    SET @v_add = CONCAT('ALTER TABLE ', tableName, '  PARTITION BY RANGE (TO_DAYS(', timeColName, '))
( PARTITION max VALUES LESS THAN MAXVALUE ENGINE = INNODB)');

    SELECT
      @v_add;
    PREPARE stmt FROM @v_add;
    EXECUTE stmt;
  END IF;

  #测试是否存在max分区
  SELECT
    COUNT(PARTITION_DESCRIPTION) INTO is_partition_exist
  FROM INFORMATION_SCHEMA.partitions
  WHERE TABLE_NAME = tableName
  AND PARTITION_DESCRIPTION = 'MAXVALUE';
  IF is_partition_exist = 0 THEN #如果没有max分区则创建之       
    SET @v_add = CONCAT('ALTER TABLE ', tableName, ' ADD PARTITION (PARTITION max VALUES LESS THAN (MAXVALUE) ENGINE = INNODB);');
    SELECT
      @v_add;
    PREPARE stmt FROM @v_add;
    EXECUTE stmt;

  END IF;

  SET p_name = CONCAT('p', DATE_FORMAT(CURDATE(), '%Y%m%d'));
  SET p_value = TO_DAYS(CURDATE()) + 1;

  #测试是否存在当日分区
  SELECT
    COUNT(PARTITION_DESCRIPTION) INTO is_partition_exist
  FROM INFORMATION_SCHEMA.partitions
  WHERE TABLE_NAME = tableName
  AND PARTITION_DESCRIPTION = p_value;

  IF is_partition_exist = 0 THEN #如果没有当日分区则创建之
    SET @v_add = CONCAT('ALTER table ', tableName
    , ' REORGANIZE PARTITION max INTO(PARTITION '
    , p_name
    , ' values less than ('
    , p_value, '),PARTITION max VALUES LESS THAN(MAXVALUE))');
    SELECT
      @v_add;
    PREPARE stmt FROM @v_add;
    EXECUTE stmt;
  END IF;
  DEALLOCATE PREPARE stmt;
END
$$

--
-- Create event `event_of_day`
--
CREATE 
	DEFINER = 'root'@'%'
EVENT event_of_day
	ON SCHEDULE EVERY '1' DAY
	STARTS '2023-01-05 05:02:52'
	DO 
BEGIN

 

call proc_create_partition_day('radpostauth','authdate');

#然后删除最早的一个分区
call proc_drop_partition( 'radpostauth',7);


END
$$

ALTER 
	DEFINER = 'root'@'%'
EVENT event_of_day
	ENABLE
$$

DELIMITER ;

--
-- Create table `nas`
--
CREATE TABLE nas (
  id int NOT NULL AUTO_INCREMENT,
  nasname varchar(128) NOT NULL,
  shortname varchar(32) DEFAULT NULL,
  type varchar(30) DEFAULT 'other',
  ports int DEFAULT NULL,
  secret varchar(60) NOT NULL DEFAULT 'secret',
  server varchar(64) DEFAULT NULL,
  community varchar(50) DEFAULT NULL,
  description varchar(200) DEFAULT 'RADIUS Client',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 9,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `nasname` on table `nas`
--
ALTER TABLE nas
ADD INDEX nasname (nasname);

--
-- Create table `admin`
--
CREATE TABLE admin (
  name varchar(45) NOT NULL,
  password varchar(45) DEFAULT NULL,
  nodeid varchar(36) DEFAULT NULL,
  role varchar(45) DEFAULT NULL,
  phone varchar(45) DEFAULT NULL,
  email varchar(45) DEFAULT NULL,
  PRIMARY KEY (name)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1638,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = '节点管理员列表';

--
-- Create index `name_UNIQUE` on table `admin`
--
ALTER TABLE admin
ADD UNIQUE INDEX name_UNIQUE (name);

-- 
-- Dumping data for table sidebar_tree
--
INSERT INTO sidebar_tree VALUES
('0a102046-7718-41e4-9724-ae7e8701f63f', 'new item', 'fe3b0289-04b4-49da-8002-f67b00143a1f', 0, 'admin'),
('0f4208c9-6fec-4a1a-a1ad-f367a414f314', '认证日志', '0a102046-7718-41e4-9724-ae7e8701f63f', 9, NULL),
('14fa6fb0-5ece-48e8-9375-434ed51e86b7', '上网账号', '0a102046-7718-41e4-9724-ae7e8701f63f', 4, NULL),
('730525d3-d608-4972-8120-c83b9d0e1530', '在线用户', '0a102046-7718-41e4-9724-ae7e8701f63f', 8, NULL),
('81034dad-ccc5-4bb9-8020-9424bc5b0eac', '根节点', '81034dad-ccc5-4bb9-8020-9424bc5bccc', 1, 'admin'),
('92628dc0-f6cd-4a84-9845-c859951390a8', '上网记录', '0a102046-7718-41e4-9724-ae7e8701f63f', 5, NULL),
('fe3b0289-04b4-49da-8002-f67b00143a1f', 'new folder', '81034dad-ccc5-4bb9-8020-9424bc5b0eac', 1, 'admin');

-- 
-- Dumping data for table realm
--
INSERT INTO realm VALUES
('f6d640c983b11421007deca6a8b9cedf', '@test', '0a102046-7718-41e4-9724-ae7e8701f63f');

-- 
-- Dumping data for table radreply
--
INSERT INTO radreply VALUES
(1, 'lkj', '@test', 'Session-Timeout', ':=', '0', '', 0),
(2, 'test01', '', 'Session-Timeout', ':=', '1', '', 0);

-- 
-- Dumping data for table radpostauth
--
-- Table radius.radpostauth does not contain any data (it is empty)

-- 
-- Dumping data for table radcheck
--
-- Table radius.radcheck does not contain any data (it is empty)

-- 
-- Dumping data for table online_user
--
-- Table radius.online_user does not contain any data (it is empty)

-- 
-- Dumping data for table offline_user
--
INSERT INTO offline_user VALUES
(149, '5380', '107ea8c600a4ef231959a68e12a741fd', 'nihao', '@test', 'NMHH-ME60-1', '10.11.31.1', 'slot=3D3D1=3D3Bsubslot=3D3D2=3D3Bport=3D3D8=3D3Bvlanid=3D3D1939=3D3Bvlanid2=3D3D68=3D3B', 'Ethernet', '2022-12-15 03:38:34', '2022-12-14 19:33:09', '2022-12-15 03:38:34', NULL, 0, 'RADIUS', '1000000000', '', 0, 0, '', 'a3:33:33:33:33:33', '', 'Framed-User', '', '10.140.10.120', '', '', '', '', NULL, 0),
(150, '5380', '1a59147017ab71f287c42581f443a340', 'test', '@test', 'NMHH-ME60-1', '10.11.31.1', 'slot=3D3D1=3D3Bsubslot=3D3D2=3D3Bport=3D3D8=3D3Bvlanid=3D3D1939=3D3Bvlanid2=3D3D68=3D3B', 'Ethernet', '2022-12-15 03:38:34', '2022-12-14 19:33:14', '2022-12-15 03:38:34', NULL, 0, 'RADIUS', '1000000000', '', 0, 0, '', 'a3:33:33:33:33:33', '', 'Framed-User', '', '10.140.10.120', '', '', '', '', NULL, 0),
(151, '5380', '4cb1afefc301c2ff35eda7bdebc84c3e', 'lkj', '@test', 'NMHH-ME60-1', '10.11.31.1', 'slot=3D3D1=3D3Bsubslot=3D3D2=3D3Bport=3D3D8=3D3Bvlanid=3D3D1939=3D3Bvlanid2=3D3D68=3D3B', 'Ethernet', '2022-12-15 04:02:30', '2022-12-15 04:00:09', '2022-12-15 04:02:30', NULL, 0, 'RADIUS', '1000000000', '', 0, 0, '', 'a3:33:33:33:33:33', '', 'Framed-User', '', '10.140.10.120', '', '', '', '', NULL, 0),
(152, '25540', '5e1b72d918bc7a3dd030b23195e7c9e2', 'dda', '@test', 'NMHH-ME60-1', '10.11.31.1', 'slot=3D3D1=3D3Bsubslot=3D3D2=3D3Bport=3D3D8=3D3Bvlanid=3D3D1939=3D3Bvlanid2=3D3D68=3D3B', 'Ethernet', '2022-12-16 00:51:03', '2022-12-15 23:50:19', '2022-12-16 00:51:03', NULL, 0, 'RADIUS', '1000000000', '', 0, 0, '', 'a3:33:33:33:33:33', '', 'Framed-User', '', '10.140.10.120', '', '', '', '', NULL, 0),
(153, '25540', '5e1b72d918bc7a3dd030b23195e7c9e2', 'dda', '@test', 'NMHH-ME60-1', '10.11.31.1', 'slot=3D3D1=3D3Bsubslot=3D3D2=3D3Bport=3D3D8=3D3Bvlanid=3D3D1939=3D3Bvlanid2=3D3D68=3D3B', 'Ethernet', '2022-12-16 07:35:48', '2022-12-16 05:18:01', '2022-12-16 07:35:48', 0, 0, 'RADIUS', NULL, NULL, 0, 0, '', 'a3:33:33:33:33:33', '', 'Framed-User', '', '10.140.10.120', '', '', '', '', NULL, 1),
(154, '25540', 'ae700701df0b57ee0516e4a20039d113', 'test', '@test', 'NMHH-ME60-1', '10.11.31.1', 'slot=3D3D1=3D3Bsubslot=3D3D2=3D3Bport=3D3D8=3D3Bvlanid=3D3D1939=3D3Bvlanid2=3D3D68=3D3B', 'Ethernet', '2022-12-16 07:35:48', '2022-12-16 05:34:08', '2022-12-16 07:35:48', 0, 0, 'RADIUS', NULL, NULL, 0, 0, '', 'a3:33:33:33:33:33', '', 'Framed-User', '', '10.140.10.120', '', '', '', '', NULL, 1),
(156, '25540', '8313dda3ef6d85a0abc7918a65ac7e9c', 'abc', '@test', 'NMHH-ME60-1', '10.11.31.1', 'slot=3D3D1=3D3Bsubslot=3D3D2=3D3Bport=3D3D8=3D3Bvlanid=3D3D1939=3D3Bvlanid2=3D3D68=3D3B', 'Ethernet', '2022-12-16 07:35:48', '2022-12-16 05:34:21', '2022-12-16 07:35:48', 0, 0, 'RADIUS', NULL, NULL, 0, 0, '', 'a3:33:33:33:33:33', '', 'Framed-User', '', '10.140.10.120', '', '', '', '', NULL, 1),
(164, '25904', '0df87ec63788d94ef983bd849a88ed0d', '003', '@test', 'NMHH-ME60-1', '10.11.31.1', 'slot=3D3D1=3D3Bsubslot=3D3D2=3D3Bport=3D3D8=3D3Bvlanid=3D3D1939=3D3Bvlanid2=3D3D68=3D3B', 'Ethernet', '2022-12-16 08:02:00', '2022-12-16 08:02:00', '2022-12-16 09:02:48', NULL, 0, 'RADIUS', '1000000000', '', 0, 0, '', 'a3:33:33:33:33:33', '', 'Framed-User', '', '10.140.10.120', '', '', '', '', NULL, 0),
(167, '25904', '27eb180821cb984d19773c773bc464d3', 'test', '@test', 'NMHH-ME60-1', '10.11.31.1', 'slot=3D3D1=3D3Bsubslot=3D3D2=3D3Bport=3D3D8=3D3Bvlanid=3D3D1939=3D3Bvlanid2=3D3D68=3D3B', 'Ethernet', '2022-12-16 08:12:08', '2022-12-16 08:12:08', '2022-12-16 09:12:48', NULL, 0, 'RADIUS', '1000000000', '', 0, 0, '', 'a3:33:33:33:33:33', '', 'Framed-User', '', '10.140.10.120', '', '', '', '', NULL, 0),
(169, '2184', '9d9d95e0082c6f6646298beb979e1323', 'test', '@test', 'NMHH-ME60-1', '10.11.31.1', 'slot=3D3D1=3D3Bsubslot=3D3D2=3D3Bport=3D3D8=3D3Bvlanid=3D3D1939=3D3Bvlanid2=3D3D68=3D3B', 'Ethernet', '2023-01-03 04:54:57', '2023-01-03 04:54:57', '2023-01-03 05:55:48', NULL, 0, 'RADIUS', '1000000000', '', 0, 0, '', 'a3:33:33:33:33:33', '', 'Framed-User', '', '10.140.10.120', '', '', '', '', NULL, 0),
(1232332, '25904', '27eb180821cb984d19773c773bc464d3', 'test', '@test', 'NMHH-ME60-1', '10.11.31.1', 'slot=3D3D1=3D3Bsubslot=3D3D2=3D3Bport=3D3D8=3D3Bvlanid=3D3D1939=3D3Bvlanid2=3D3D68=3D3B', 'Ethernet', '2022-12-11 19:05:25', '2022-12-16 07:48:16', '2022-12-16 07:50:26', NULL, 391501, 'RADIUS', '', '1000000000', 4981849538, 68448711107, '', 'a3:33:33:33:33:33', '', 'Framed-User', '', '10.140.10.120', '', '', '', '', NULL, 0),
(1232333, '25904', 'bd7708610152765336b1560576fc5691', '001', '@test', 'NMHH-ME60-1', '10.11.31.1', 'slot=3D3D1=3D3Bsubslot=3D3D2=3D3Bport=3D3D8=3D3Bvlanid=3D3D1939=3D3Bvlanid2=3D3D68=3D3B', 'Ethernet', '2022-12-11 19:06:07', '2022-12-16 07:51:08', '2022-12-16 07:51:08', NULL, 391501, 'RADIUS', '', '1000000000', 4981849538, 68448711107, '', 'a3:33:33:33:33:33', '', 'Framed-User', '', '10.140.10.120', '', '', '', '', NULL, 0),
(1232334, '25904', '0df87ec63788d94ef983bd849a88ed0d', '003', '@test', 'NMHH-ME60-1', '10.11.31.1', 'slot=3D3D1=3D3Bsubslot=3D3D2=3D3Bport=3D3D8=3D3Bvlanid=3D3D1939=3D3Bvlanid2=3D3D68=3D3B', 'Ethernet', '2022-12-11 19:16:50', '2022-12-16 07:59:44', '2022-12-16 08:01:51', NULL, 391501, 'RADIUS', '', '1000000000', 4981849538, 68448711107, '', 'a3:33:33:33:33:33', '', 'Framed-User', '', '10.140.10.120', '', '', '', '', NULL, 0),
(1232335, '25904', '18ab6291fcfcda3e917a5d0ad142719d', '004', '@test', 'NMHH-ME60-1', '10.11.31.1', 'slot=3D3D1=3D3Bsubslot=3D3D2=3D3Bport=3D3D8=3D3Bvlanid=3D3D1939=3D3Bvlanid2=3D3D68=3D3B', 'Ethernet', '2022-12-11 19:24:18', '2022-12-16 08:00:52', '2022-12-16 08:09:19', NULL, 391501, 'RADIUS', '', '1000000000', 4981849538, 68448711107, '', 'a3:33:33:33:33:33', '', 'Framed-User', '', '10.140.10.120', '', '', '', '', NULL, 0),
(1232336, '2184', '9d9d95e0082c6f6646298beb979e1323', 'test', '@test', 'NMHH-ME60-1', '10.11.31.1', 'slot=3D3D1=3D3Bsubslot=3D3D2=3D3Bport=3D3D8=3D3Bvlanid=3D3D1939=3D3Bvlanid2=3D3D68=3D3B', 'Ethernet', '2022-12-29 16:06:20', '2023-01-03 04:51:21', '2023-01-03 04:51:21', NULL, 391501, 'RADIUS', '', '1000000000', 4981849538, 68448711107, '', 'a3:33:33:33:33:33', '', 'Framed-User', '', '10.140.10.120', '', '', '', '', NULL, 0);

-- 
-- Dumping data for table nas
--
INSERT INTO nas VALUES
(1, '*', 'any', 'other', NULL, 'test', '', NULL, 'RADIUS Client');

-- 
-- Dumping data for table admin
--
INSERT INTO admin VALUES
('admin', '123456', '81034dad-ccc5-4bb9-8020-9424bc5b0eac', 'admin', NULL, NULL),
('dadada', '123456', '81034dad-ccc5-4bb9-8020-9424bc5b0eac', 'admin', '13424133093', 'liukaijie1980@gmail.com'),
('liukaijie', '123456', '0a102046-7718-41e4-9724-ae7e8701f63f', 'admin', '13570263044', '20786897@qq.com'),
('test001', 'test002', '81034dad-ccc5-4bb9-8020-9424bc5b0eac', 'admin', '13570263044', 'liukaijie1980@gmail.com'),
('test002', 'test002', '81034dad-ccc5-4bb9-8020-9424bc5b0eac', 'editor', '13570263044', 'liukaijie1980@gmail.com'),
('test003', 'test003', '81034dad-ccc5-4bb9-8020-9424bc5b0eac', 'admin', '13570263044', 'liukaijie1980@gmail.com'),
('test004', 'test004', '81034dad-ccc5-4bb9-8020-9424bc5b0eac', 'admin', '13424133093', 'liukaijie1980@gmail.com'),
('test005', 'test001', '81034dad-ccc5-4bb9-8020-9424bc5b0eac', 'admin', '13424133093', 'liukaijie1980@gmail.com'),
('test008', 'test001', '0a102046-7718-41e4-9724-ae7e8701f63f', 'admin', '13345678933', '20786897@qq.com'),
('test009', 'test001', '0a102046-7718-41e4-9724-ae7e8701f63f', 'admin', '13333333333', '20786897@qq.com');

-- 
-- Dumping data for table account_info
--
INSERT INTO account_info VALUES
('1597284030057648130', 'zhaoqing', '@zhaoqing', 'zhaoqing', 0000000000, 0, 'admin', NULL, NULL, '2022-11-29 01:53:40', 1, 0, -4000, 0, 0, 0, '', 3600),
('1597284130351845377', 'foshan', '@foshan', 'foshan', 0000000000, 0, 'admin', '2022-11-29 01:39:47', NULL, '2022-11-29 01:39:47', 1, 0, -4000, 0, 0, 0, '', 3600),
('1602419559736827905', 'test', '@test', 'test', 0000000000, 0, 'admin', '2022-12-13 05:46:09', NULL, '2022-12-13 05:46:09', 1, 0, 0, 0, 0, 0, '', 1800);

--
-- Set default database
--
USE radius;

--
-- Drop trigger `offline_user_BEFORE_INSERT`
--
DROP TRIGGER IF EXISTS offline_user_BEFORE_INSERT;

--
-- Drop trigger `offline_user_BEFORE_UPDATE`
--
DROP TRIGGER IF EXISTS offline_user_BEFORE_UPDATE;

--
-- Drop trigger `online_user_BEFORE_INSERT`
--
DROP TRIGGER IF EXISTS online_user_BEFORE_INSERT;

--
-- Drop trigger `online_user_BEFORE_UPDATE`
--
DROP TRIGGER IF EXISTS online_user_BEFORE_UPDATE;

--
-- Drop trigger `radpostauth_BEFORE_INSERT`
--
DROP TRIGGER IF EXISTS radpostauth_BEFORE_INSERT;

--
-- Drop trigger `radpostauth_BEFORE_UPDATE`
--
DROP TRIGGER IF EXISTS radpostauth_BEFORE_UPDATE;

--
-- Set default database
--
USE radius;

DELIMITER $$

--
-- Create trigger `radpostauth_BEFORE_UPDATE`
--
CREATE
DEFINER = 'root'@'%'
TRIGGER radpostauth_BEFORE_UPDATE
BEFORE UPDATE
ON radpostauth
FOR EACH ROW
BEGIN
  #将radius进程传入的原始username，如格式为abc@realm 则改为 abc 存入 username, @realm 存入realm 字段
  IF INSTR(new.username, "@") > 0
    AND INSTR(new.realm, "@") = 0 THEN
    SET new.realm = SUBSTR(new.username, INSTR(new.username, "@"));
    SET new.username = LEFT(new.username, INSTR(new.username, "@") - 1);
  END IF;
END
$$

--
-- Create trigger `radpostauth_BEFORE_INSERT`
--
CREATE
DEFINER = 'root'@'%'
TRIGGER radpostauth_BEFORE_INSERT
BEFORE INSERT
ON radpostauth
FOR EACH ROW
BEGIN
  #将radius进程传入的原始username，如格式为abc@realm 则改为 abc 存入 username, @realm 存入realm 字段
  IF INSTR(new.username, "@") > 0
    AND INSTR(new.realm, "@") = 0 THEN
    SET new.realm = SUBSTR(new.username, INSTR(new.username, "@"));
    SET new.username = LEFT(new.username, INSTR(new.username, "@") - 1);
  END IF;
END
$$

--
-- Create trigger `online_user_BEFORE_UPDATE`
--
CREATE
DEFINER = 'root'@'%'
TRIGGER online_user_BEFORE_UPDATE
BEFORE UPDATE
ON online_user
FOR EACH ROW
BEGIN
  #将radius进程传入的原始username，如格式为abc@realm 则改为 abc 存入 username, @realm 存入realm 字段
  IF INSTR(new.username, "@") > 0
    AND INSTR(new.realm, "@") = 0 THEN
    SET new.realm = SUBSTR(new.username, INSTR(new.username, "@"));
    SET new.username = LEFT(new.username, INSTR(new.username, "@") - 1);
  END IF;



END
$$

--
-- Create trigger `online_user_BEFORE_INSERT`
--
CREATE
DEFINER = 'root'@'%'
TRIGGER online_user_BEFORE_INSERT
BEFORE INSERT
ON online_user
FOR EACH ROW
BEGIN
  #将radius进程传入的原始username，如格式为abc@realm 则改为 abc 存入 username, @realm 存入realm 字段
  IF INSTR(new.username, "@") > 0
    AND INSTR(new.realm, "@") = 0 THEN
    SET new.realm = SUBSTR(new.username, INSTR(new.username, "@"));
    SET new.username = LEFT(new.username, INSTR(new.username, "@") - 1);
  END IF;

END
$$

--
-- Create trigger `offline_user_BEFORE_UPDATE`
--
CREATE
DEFINER = 'root'@'%'
TRIGGER offline_user_BEFORE_UPDATE
BEFORE UPDATE
ON offline_user
FOR EACH ROW
BEGIN
  #将radius进程传入的原始username，如格式为abc@realm 则改为 abc 存入 username, @realm 存入realm 字段
  IF INSTR(new.username, "@") > 0
    AND INSTR(new.realm, "@") = 0 THEN
    SET new.realm = SUBSTR(new.username, INSTR(new.username, "@"));
    SET new.username = LEFT(new.username, INSTR(new.username, "@") - 1);
  END IF;

  IF new.acctsessiontime IS NOT NULL
    AND new.acctsessiontime != 0 THEN
    SET new.acctstarttime = DATE_SUB(new.acctstoptime, INTERVAL new.acctsessiontime SECOND);
    # 扣减剩余时长
    UPDATE account_info
    SET second_remain = (second_remain - new.acctsessiontime)
    WHERE user_name = new.username
    AND realm = NEW.realm
    AND second_remain > 0;
  ELSE
    #radius 没有传入acctsessiontime字段要从online_user表中取出对应的上线时间。  
    SET @starttime := new.acctstoptime;
    SELECT
      acctstarttime INTO @starttime
    FROM online_user
    WHERE acctsessionid = new.acctsessionid LIMIT 1;
    SET new.acctstarttime := @starttime;
    # 扣减剩余时长
    UPDATE account_info
    SET second_remain = (second_remain - (new.acctstoptime - new.acctstarttime))
    WHERE user_name = new.username
    AND realm = NEW.realm
    AND second_remain > 0;
  END IF;

  #扣减剩余流量
  UPDATE account_info
  SET byte_remain = (byte_remain - new.acctinputoctets - new.acctoutputoctets)
  WHERE user_name = new.username
  AND realm = NEW.realm
  AND byte_remain > 0;

  #该用户已经下线，所以从online_user表中删除对应表项
  DELETE
    FROM online_user
  WHERE acctsessionid = new.acctsessionid
    AND username = new.username
    AND realm = new.realm;
END
$$

--
-- Create trigger `offline_user_BEFORE_INSERT`
--
CREATE
DEFINER = 'root'@'%'
TRIGGER offline_user_BEFORE_INSERT
BEFORE INSERT
ON offline_user
FOR EACH ROW
BEGIN
  #将radius进程传入的原始username，如格式为abc@realm 则改为 abc 存入 username, @realm 存入realm 字段
  IF INSTR(new.username, "@") > 0
    AND INSTR(new.realm, "@") = 0 THEN
    SET new.realm = SUBSTR(new.username, INSTR(new.username, "@"));
    SET new.username = LEFT(new.username, INSTR(new.username, "@") - 1);
  END IF;

  IF new.acctsessiontime IS NOT NULL
    AND new.acctsessiontime != 0 THEN
    SET new.acctstarttime = DATE_SUB(new.acctstoptime, INTERVAL new.acctsessiontime SECOND);
    # 扣减剩余时长
    UPDATE account_info
    SET second_remain = (second_remain - new.acctsessiontime)
    WHERE user_name = new.username
    AND realm = NEW.realm
    AND second_remain > 0;
  ELSE
    #radius 没有传入acctsessiontime字段要从online_user表中取出对应的上线时间。  
    SET @starttime := new.acctstoptime;
    SELECT
      acctstarttime INTO @starttime
    FROM online_user
    WHERE acctsessionid = new.acctsessionid LIMIT 1;
    SET new.acctstarttime := @starttime;
    # 扣减剩余时长
    UPDATE account_info
    SET second_remain = (second_remain - (new.acctstoptime - new.acctstarttime))
    WHERE user_name = new.username
    AND realm = NEW.realm
    AND second_remain > 0;
  END IF;

  #扣减剩余流量
  UPDATE account_info
  SET byte_remain = (byte_remain - new.acctinputoctets - new.acctoutputoctets)
  WHERE user_name = new.username
  AND realm = NEW.realm
  AND byte_remain > 0;

  #该用户已经下线，所以从online_user表中删除对应表项
  DELETE
    FROM online_user
  WHERE acctsessionid = new.acctsessionid
    AND username = new.username
    AND realm = new.realm;

END
$$

DELIMITER ;

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;